---
- name: Create Coin Config Directory
  file: 
    path: "{{ coin_datadir }}"
    state: directory

- name: "Generate Coin Config"
  template:
    src: coin.conf.j2
    dest: "{{ coin_config_file }}"

- name: "Download Wallet"
  unarchive:
    src: https://github.com/Ruxiol/ruxcryptoRXC/releases/download/v1.0.4/RXC-linux.zip
    dest: /tmp
    remote_src: yes

- name: "Copy Wallet"
  shell: "cp /tmp/RXC-linux/* /usr/local -R"
  
- name: Install Coin Systemd
  become: true
  template:
    src: "coin.service.j2"
    dest: "/lib/systemd/system/{{ coin_name }}.service"
    force: true

- name: Enable Coin Daemon
  become: true
  service:
    name: "{{ coin_name }}"
    enabled: true
    daemon_reload: yes
    state: started
